
-- Add missing columns to student_info table
ALTER TABLE public.student_info 
ADD COLUMN gender text,
ADD COLUMN birth_date date,
ADD COLUMN birth_place text,
ADD COLUMN birth_country text,
ADD COLUMN blood_type text,
ADD COLUMN health_insurance text,
ADD COLUMN origin_institution_campus text,
ADD COLUMN origin_faculty text,
ADD COLUMN student_code text,
ADD COLUMN cumulative_gpa numeric,
ADD COLUMN academic_director_name text,
ADD COLUMN academic_director_phone text,
ADD COLUMN academic_director_email text;

-- Make application_number nullable since it's auto-generated by trigger
ALTER TABLE public.mobility_applications 
ALTER COLUMN application_number DROP NOT NULL;
